# Generated by Django 4.1.3 on 2022-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarterListDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ascendancy', models.CharField(max_length=20)),
                ('main_skill', models.CharField(max_length=50)),
                ('description_build', models.TextField()),
                ('survivability', models.CharField(max_length=20)),
                ('img_character', models.ImageField(upload_to='character/%Y/%m/%d/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
